// Generated by CoffeeScript 1.6.3
var $, Alloy;

Alloy = require('alloy');

$ = Alloy.createController('index');

describe('index controller', function() {
  beforeEach(function() {});
  return describe('display', function() {
    return it("label", function() {
      return expect($.__views.label.text).toEqual('Hello, World');
    });
  });
});
